services:
  db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  rails:
    build:
      context: .
      dockerfile: Dockerfile.rails
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true
    command: ruby rails_minimal.rb

volumes:
  postgres_data: